remap_politics = {'liberal':'liberal',
'conservative':'conservative',
'neutral':'non-aligned',
'liberal; moderate':'liberal',
'radical':'radical', 
'whig':'liberal',
'tory':'conservative',
'liberal; liberal':'liberal',
'tory; old':'conservative',
'independent':'independent',
'repeal':'irish nationalist', 
'liberal; free-trade':'liberal',
'high; tory':'conservative',
'liberal; conservative':'non-aligned',  # ??
'ultra; liberal':'liberal',
 'no-politics':'non-aligned',
'protestant; conservative':'conservative',
'evangelical':'denominational', 
'protestant':'denominational',
'liberal; independent':'liberal',
'liberal; ultra':'liberal',
'roman-catholic; ultramontane':'denominational', 
'independent; liberal':'liberal',
'neutral; neutral':'non-aligned', 
'national':'irish nationalist', 
'ultramontane':'denominational', 
'constitutional':'conservative',
'anti-whig':'conservative', # ??
'independent; conservative':'conservative',
'tory; neutral':'non-aligned',
'neutral; national':'non-aligned', 
'moderate; conservative':'conservative',
'catholic; national':'denominational',  # ??
'liberal; non-comformist':'liberal',
'conservative; liberal':'non-aligned', # ?? 
'advanced; liberal; non-comformist':'liberal',
'moderate; liberal':'liberal', 
'catholic':'denominational', 
'utlra; liberal':'liberal', 
'republican':'liberal', # ??
'orange':'denominational', # ?? 
'presbyterian':'denominational',
 'advanced; liberal':'liberal',
'conservative; conservative':'conservative', 
'independent; li':'liberal',
'independent; protestant':'denominational', 
'independent; advanced; liberal':'liberal',
'llberal; conservative':'conservative', # changed because theses switched very often and not to neutral
'conservative; independent':'conservative',
'national; independent':'irish nationalist', 
'irish; national; catholic':'irish nationalist',
'non-political':'non-aligned', 
'liberal; conservative; independent':'liberal',
'church-of-ireland':'denominational', 
'liberal; tory; independent':'liberal', 
'unionist':'conservative',
'liberal; unionist':'conservative', 
'non-party':'non-aligned', 
'national; catholic':'denominational',
'tory; liberal':'liberal', 
'roman; catholic':'denominational', 
'orange; protestant':'denominational',
'independent; constitutional':'conservative', 
'conservative; unionist':'conservative',
'conservative; constitutional':'conservative', 
'radical; advanced; liberal':'radical', # ??
'nationalist':'irish nationalist', 
'church of england':'denominational', 
'liberal; radical':'radical', # ??
'industrial':'other', # ?? 
'non-political; non-sectarian': 'non-aligned', # ??
'independent; nationalist':'irish nationalist', 
'nationalist; nationalist':'irish nationalist',
'progressive':'non-aligned', # ?? 
'church-of-england':'denominational', 
'roman-catholic':'denominational',
'nationalist; liberal':'liberal', # ?? 
'national; liberal':'liberal',
'unionist; conservative': 'conservative', 
'liberal; radical; labour':'labour', # ??
'unionist; liberal':'conservative', 
'unionist; independent':'conservative', 
'church-of-irelad':'denominational'}

convert_price = {'1d':1, '2d':2 ,'½ d':.5,'3d':3,
    '1 ½ d':1.5, '6d':6,'4d':4, 
    '5d':5, '3 ½ d':3.5, '4 ½ d':4.5,
    '2 ½ d':2.5, '1s':12, 'Gratis':.0, 
    '9d':9, '7d':7, '8d':8, 'gratis':0, 
    '5s':60, '21s':252, '10s':120, '20s':240, 
    '2s':24, '8s':96, '£ 3 3s':756, '12s':144, 
    '1':1,'One Halfpenny':.5, '1 ½':1.5, 
    '26s':312, '7s':84,'½<CON>d':.5, 
    '2':2,'£ 1 12s':384,'24s':288, 
    '3 ½':3.5,'15s':189, 'Halfpenny':.5,
    '£ 1 19s':468,'40s':480,'1 ½ 4':1.5,
    '13s':156, '£ 1 10s':360, '6':6, 
    ' ½ d':.5, '6s':72,'Gra':0, 
    '42s':504,'5 ½ d':5.5,'One Penny':1,
    'Sixpence':72, '£ 2 2s':504, '£2 ':480,
    '4s':48,'£ 1 5s':252,'£ 2 16s':672 ,
    '4 ½':4.5,'3s':36}